name: Install sigrok-cli (Matrix)

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            install_cmd: choco install -y
            pkg: sigrok-cli

          - os: macos-latest
            install_cmd: brew install
            pkg: sigrok-cli

          - os: ubuntu-latest
            install_cmd: sudo apt-get update && sudo apt-get install -y
            pkg: sigrok-cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sigrok-cli
        shell: bash
        run: |
          ${{ matrix.install_cmd }} ${{ matrix.pkg }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install custom decoders
        run: |
          mkdir -p /usr/share/libsigrokdecode/decoders

          # Copy your decoder directories here
          cp -r {max6958,xbox_one_sb_post,xbox_one_soc_post} /usr/share/libsigrokdecode/decoders/

      - name: Verify decoder installation
        run: |
          ls -la /usr/share/libsigrokdecode/decoders

      - name: Smoke test sigrok-cli
        run: |
          sigrok-cli --version
          sigrok-cli --protocol-decoders

      - name: Run with sample trace
        run: sigrok-cli -i i2c_trace.sr -P "i2c:sda=SOC SDA:scl=SOC SCL,xbox_one_soc_post"|grep -E 'xbox_one_soc_post'
